### PR TITLE
Fix logging response to match 2.0 syntax.

### PR DESCRIPTION
**Pull request by geppettodivacin**
Documentation can be found at
http://docs.couchdb.org/en/2.0.0/query-server/protocol.html

Previously, the server had been receiving indecipherable errors complaining about an unrecognized response and printing the entire traceback in repr() format. The new format properly either sends an error message back to the client or prints a log message to the console.

### CODE REVIEW

**Comment by djc** [comment]
My question here is about 1.x vs 2.x compatibility. CouchDB-Python must still support CouchDB-1.0. Is the logging part of the protocol the same in both of these versions, or did something change?

**Comment by geppettodivacin** [comment]
As I have only used CouchDB for the last few weeks, I assumed that you had been using the correct syntax for 1.x. However, according to the docs, at least as far back as 1.5, it uses the list format for errors and logging.

http://docs.couchdb.org/en/1.6.0/query-server/protocol.html

http://docs.couchdb.org/en/1.5.0/query-server/protocol.html

**Comment by geppettodivacin** [comment]
Is there anything I should change about this PR before it's merged in?

**Comment by djc** [comment]
Nope, I just needed a little time to review this again! Thanks!

**Pull request merged**
